# This is a basic workflow to help you get started with Actions
name: Test
on:
  push:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: test_navbar
        run: pytest test_navbar.py
