name: Test_mrg
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: main
  schedule:
    - cron: "0 7 * * *"

jobs:
  test_2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - run: python -m pip install --upgrade pip
    - run: pip install -r requirements.txt
    
    - run: pytest tests/test_sidebar_receipts.py
    
#     - name: my artifact
#       uses: actions/download-artifact@v2
#       with:
#         path: tests
#     - run: ls -R
#       working-directory: tests
#       # Use always() to always run this step to publish test results when there are test failures
#       if: ${{ always() }}
      
    - run: pytest tests/test_file_in_dir.py
    - run: ls -R
      working-directory: tests
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

        
