name: Test_mrg
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: main
  schedule:
    - cron: "0 7 * * *"

jobs:
  add_ls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    
    - run: gpg --symmetric --cipher-algo AES256 tests/config.json
    - run: python -m pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: pytest --alluredir result
      
#     - run: pytest tests/test_navbar.py
#     - run: pytest tests/test_settings.py
#     - run: pytest tests/test_sidebar_accruals.py
#     - run: pytest tests/test_sidebar_appeals.py
#     - run: pytest tests/test_sidebar_counters.py
#     - run: pytest tests/test_sidebar_main.py
#     - run: pytest tests/test_sidebar_payment.py
#     - run: pytest tests/test_sidebar_receipts.py
#     - run: pytest tests/test_welcome.py
  
        
