# This is a basic workflow to help you get started with Actions
name: Test
on:
  push:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test_
        run: |
         python --version
         selenium --version
        
