name: Test_mrg
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: main
  schedule:
    - cron: "0 7 * * *"

jobs:
  test_pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - run: python -m pip install --upgrade pip
    - run: pip install -r requirements.txt
   
    - run: pytest
      
    - name: my artifact     
      uses: actions/download-artifact@v2
      with:
        path: tests
    
      
  test_2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - run: python -m pip install --upgrade pip
    - run: pip install -r requirements.txt
    - name: Display structure of downloaded files
      run: |
        pytest tests/test_sidebar_receipts.py
        ls -R
      working-directory: tests
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
#     - run: pytest tests/test_navbar.py
#     - run: pytest tests/test_settings.py
#     - run: pytest tests/test_sidebar_accruals.py
#     - run: pytest tests/test_sidebar_appeals.py
#     - run: pytest tests/test_sidebar_counters.py
#     - run: pytest tests/test_sidebar_main.py
#     - run: pytest tests/test_sidebar_payment.py
#     - run: pytest tests/test_sidebar_receipts.py
#     - run: pytest tests/test_welcome.py
  
        
